version: '2.1'

services:
  todo-frontend-vue:
    build: .
    image: todo-frontend-vue
    ports:
      - 80:80
    environment:
      - VUE_APP_BACKEND_HOST=http://todomvc.go:8080/todos/

  todo-backend-golang:
    hostname: todomvc.go
    image: tullo/todo-backend-golang
    ports:
      - 8080:8080
