apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
    - name: "todo-frontend"
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: todo-frontend